- README.md
> remove GAMS documentation link because it stopped working

- src/CbcSolverInterface.jl
Implement getobjgap acording to the [mathprogbase docs](http://mathprogbasejl.readthedocs.org/en/latest/lowlevel.html#getobjgap). Should there be a check for almost zero?
> Implement getobjgap

- REQUIRE
- src/CbcSolverInterface.jl
- test/runtests.jl
> implement MathProgBase.setparameters

- README.md
- src/CbcSolverInterface.jl
- test/REQUIRE
@chriscoey
https://github.com/mlubin/Pajarito.jl/issues/302
> option to not check warmstarts

- .travis.yml
Adding the current stable version to travis CI
> Adding 0.6 version to CI

- REQUIRE
- deps/build.jl
- examples/knapsack.jl
- src/CbcCInterface.jl
- test/MOIWrapper.jl
- test/runtests.jl
This should take Cbc at least part of the way to Julia 0.7.
> Fix Julia 0.7 deprecations.

- .travis.yml
> test and allow travis failures on 1.0

- .travis.yml
- deps/build.jl
> fix build on Julia 1.0

- src/CbcCInterface.jl
- src/CbcSolverInterface.jl
And a deprecation fix.
Ref https://github.com/JuliaOpt/JuMP.jl/pull/1477#issuecomment-423705275
> Fix setwarmstart

- src/CbcSolverInterface.jl
Needed for https://github.com/StructJuMP/StructJuMP.jl/pull/62
> Julia v1.0 updates

- README.md
Identical to https://github.com/JuliaOpt/Clp.jl/pull/41
> Add COIN-OR logo to readme

- src/MPBWrapper.jl
@kaarthiksundar, does this fix the issue?
> fix setparameters when options is empty on Julia 1.0

- src/MOIWrapper.jl
Sorry for the large white-space diff. The second commit has the relevant change.
Closes #86
> Add DualStatus

- src/MOI_wrapper.jl
> NoSolution -> NO_SOLUTION

- src/MOI_wrapper.jl
> Remove redundant implementation

- Project.toml
- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
See https://github.com/JuliaOpt/MathOptInterface.jl/issues/736
> Update to MOI v0.9

- .travis.yml
- Project.toml
- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Update to MOI v0.9.5

- README.md
> Fix readme JuMP link

- Project.toml
- scripts/Project.toml
- scripts/clang.jl
- src/gen/libcbc_api.jl
> Bump to Cbc 2.10.5

- test/MOI_wrapper.jl
> Add test for threads parameter

- LICENSE.md
- scripts/clang.jl
- src/Cbc.jl
- src/MOI_wrapper/MOI_wrapper.jl
- src/gen/libcbc_api.jl
- src/gen/libcbc_common.jl
- test/MOI_wrapper.jl
- test/runtests.jl
x-ref: https://github.com/jump-dev/AmplNLWriter.jl/pull/155
> Add copyright headers

- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI_wrapper.jl
- test/segfault.mof.json
> Add test for segfault issue

- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Change SetVariableNames to default false

- test/MOI_wrapper.jl
I remember why I haven't chased this down: I can't reproduce it locally.
x-ref https://github.com/jump-dev/Cbc.jl/issues/199
> Skip segfaulting test on macos

- README.md
I wonder if it makes sense to update the list with everything, not just for which `MOI.supports` is defined.
> Update README with support attributes

- test/MOI_wrapper.jl
x-ref https://github.com/jump-dev/MathOptInterface.jl/pull/2410
> Remove ZerosBridge
