jump-dev/Cbc.jl

deps/build.jl
test/REQUIRE
test/runtests.jl

--enable-dependency-linking is supposedly default now, but removing
it did not work, libClp was not linked correctly to libCoinUtils
I was not expecting this at all, but the latest version of OS (2.9.0) fails a Clp-related unit test if you try to use it with the few-months-old version of Cbc (2.8.12) that we've been using here.

Use latest version 2.9.1

---

src/Cbc.jl

this allows installing in a non-default location
ref https://github.com/JuliaLang/julia/issues/8679#issuecomment-75796502

Use relative path for deps.jl check

---

deps/build.jl

Homebrew is already running on 2.9.7 which should be good enough.
@tkelman, looks like opensuse is on 2.9.2, would it be hard to bump?

bump source to 2.9.8

---

src/CbcSolverInterface.jl
test/REQUIRE
test/runtests.jl

This was a bad idea and blocks tests from passing on 0.7 (https://github.com/JuliaOpt/Cbc.jl/pull/60).
Also fixes option handling which as the other blocker to get tests passing. CC @GunnarFarneback

don't run JuMP's tests

---

src/CbcSolverInterface.jl
src/MOIWrapper.jl

Replace the deprecated `importall` with specific imports and module prefixed extensions.
Second commit deals with warnings from moving sparse functionality to `stdlib` in Julia 0.7.

No more importall

---

REQUIRE
src/MOIWrapper.jl
test/MOIWrapper.jl
test/runtests.jl

Tests linear15 were disables because they are using `VectorAffineFunction`.
All tests are passing with MOI 0.6 in OSX using Julia 0.6 and Julia 0.7

Updating wrapper for MOI 0.6

---

src/MOI_wrapper.jl

If an `Int64` is provided that is too large to fit in an `Int32`, there will be an explicit error
```julia
julia> convert(Int32, 1 << 60)
ERROR: InexactError: trunc(Int32, 1152921504606846976)
Stacktrace:
[1] top-level scope at none:0
```
Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/612

Allow 64-bit int input in 32-bit system

---

REQUIRE
src/MOI_wrapper.jl
test/MOI_wrapper.jl
test/runtests.jl

This PR closes *all* outstanding MOI related issues and gets Cbc in a nice shape for JuMP 0.19 release.
It was easier to just tidy up the wrapper in one shot that have many PRs sitting in CI.
Closes #107 
Closes #106
Closes #104 
<s>Closes #102</s>
Closes #96
Closes #81
Closes #79

A thorough modernization of the MOI wrapper

---

README.md

See https://discourse.julialang.org/t/solved-how-do-i-use-cbc-with-jump-0-19/25502

Update readme with Cbc.Optimizer

---

.travis.yml
Project.toml

While not used directly in the source code, the tests are including a file from another package which does require Compat.

Add Compat to test dependencies

---

src/MOI_wrapper.jl
test/MOI_wrapper.jl

Currently, `MOI.copy_to` ignores attribute that it does not know instead of throwing an `UnsupportedAttribute` error.
This PR pass the attributes and adds the skeleton for supporting starting values in https://github.com/JuliaOpt/Cbc.jl/pull/128/

Pass attributes instead of ignoring them

---

src/CbcCInterface.jl
src/MOI_wrapper.jl
src/MPB_wrapper.jl
test/MOI_wrapper.jl

This PR adds the recently added Cbc function `setMIPStartI` to `CbcCInterface` and uses it in the MPB `setwarmstart!` function instead of `setInitialSolution`.
As a result the Cbc warmstart becomes silent, which solves #78 and possibly also #41, although that issue is very vague on details.

Use setMIPStartI function for warmstart.

---

.travis.yml
Project.toml
appveyor.yml
src/MOI_wrapper.jl

Should improve the timing of https://medium.com/@vanstark88/construction-speed-in-popular-open-source-math-modeling-tools-712fd841fc50
The following code:
```julia
N = 100000
model = MOIU.Model{Float64}()
x = MOI.add_variables(model, N)
MOI.add_constraints(model, MOI.SingleVariable.(x), [MOI.Integer() for i in 1:N])
optimizer = Cbc.Optimizer()
@time MOI.copy_to(optimizer, model);
```
gives
```
0.267909 seconds (1.40 M allocations: 47.611 MiB)
```
with master and gives
```
0.148257 seconds (201.01 k allocations: 29.324 MiB, 16.74% gc time)
```
with this PR
Note that the number of allocation was divided by 7.

Add function barrier for type instability in constraint copy

---

src/MOI_wrapper/MOI_wrapper.jl

This extension makes it possible to call `JuMP.relative_gap(model)` if `model` is a `JuMP.Model` that was solved by Cbc.

Support MOI.RelativeGap

---

src/MOI_wrapper/MOI_wrapper.jl
test/MOI_wrapper.jl

Closes #142 
I couldn't find anything suggesting that Cbc will return an `INFEASIBLE_POINT`, so we just assume that if `Cbc_numberSavedSolutions(model) == 1`, then there is a feasible solution.

Return correct PrimalStatus when solve terminates before optimality

---

src/Cbc.jl

Enable Cbc.jl to work with the `devel` version of Cbc.  Closes #152

Allow devel version of Cbc

---

README.md

The new JLLs make it possible to access the executable (not just the libraries) from Julia!

[README] Add advice on running the Cbc executable

---

src/MOI_wrapper/MOI_wrapper.jl

Closes #172 
Closes #173 
```Julia
julia> bench();
Optimal - objective value 4.50015e+08
Optimal objective 450015000 - 0 iterations time 0.002
4.113598 seconds (60.00 k allocations: 2.976 MiB)
```
```Julia
julia> bench();
Optimal - objective value 4.50015e+08
Optimal objective 450015000 - 0 iterations time 0.002
0.000598 seconds (4 allocations: 234.547 KiB)
```
```Julia
using Cbc
const MOI = Cbc.MOI
function bench(N = 30_000)
cbc = Cbc.Optimizer()
model = MOI.Utilities.CachingOptimizer(MOI.Utilities.Model{Float64}(), cbc)
x = MOI.add_variables(model, N);
MOI.add_constraints(model, x, MOI.GreaterThan.(1.0:N));
MOI.set(model, MOI.ObjectiveSense(), MOI.MIN_SENSE);
f = MOI.ScalarAffineFunction(MOI.ScalarAffineTerm.(1.0, x), 0.0);
MOI.set(model, MOI.ObjectiveFunction{typeof(f)}(), f); …
```

Fix performance issue

---

README.md

In the spirit of https://github.com/jump-dev/MathOptInterface.jl/issues/1633, I'm going to try and unify a lot of the READMEs.

Various updates to README

---

Project.toml

This shouldn't have been 0.10
I also want to check if the new Cbc_jll works on all platforms.

Bump minimum version of MOI

---

src/MOI_wrapper/MOI_wrapper.jl
test/MOI_wrapper.jl

Update to MatrixOfConstraints

---

src/MOI_wrapper/MOI_wrapper.jl
test/MOI_wrapper.jl

Ignore threads parameter on Windows

---

Project.toml

Matches https://github.com/jump-dev/Clp.jl/pull/133, we experienced a similar downgrade of Cbc_jll and are running into `libdmumps.so: cannot open shared object file: No such file or directory`
Closes #196

Update to Cbc_jll dep to fix Clp_jll compatibility with MUMPS

---

src/MOI_wrapper/MOI_wrapper.jl
test/MOI_wrapper.jl

Closes #208
@matbesancon is this what you were looking for?

Pass variable names to solver in copy_to

---

Project.toml
src/MOI_wrapper/MOI_wrapper.jl

Add support for MOI.AbsoluteGapTolerance and MOI.RelativeGapTolerance

---

src/MOI_wrapper/MOI_wrapper.jl

Add support for MOI.NumberOfThreads
